### ISSUE TITLE
NoSuchMethodError `Instrumented.fileCollectionObserved` upgrading to Gradle 8

### ISSUE THREAD

**Issue by jarohen** [clojurephant/clojurephant#206]
## Expected Behavior

`./gradlew` (no args) prints standard help text

## Current Behavior

```
java.lang.NoSuchMethodError: 'void org.gradle.internal.classpath.Instrumented.fileCollectionObserved(org.gradle.api.file.FileCollection, java.lang.String)'
        at dev.clojurephant.plugin.clojure.ClojureBuild.getAllNamespaces(ClojureBuild.java:32)
        at dev.clojurephant.plugin.clojure.ClojureBuild_Decorated.getAllNamespaces(Unknown Source)
        at dev.clojurephant.plugin.clojure.ClojureBuild.checkAll(ClojureBuild.java:39)
        at dev.clojurephant.plugin.clojure.ClojurePlugin.configureBuilds(ClojurePlugin.java:22)
        at dev.clojurephant.plugin.clojure.ClojurePlugin.apply(ClojurePlugin.java:17)
        at dev.clojurephant.plugin.clojure.ClojurePlugin.apply(ClojurePlugin.java:10)
```

## Context

Gradle 8 is unusable. Works using 7.6

## Environment

- **Build scan URL:**
- **clojurephant version:** 0.8.0-beta.2
- **Gradle version:** 8.1+
- **Java version:** 17
- **OS version:** Manjaro

**Comment by jarohen** [comment]
Cheers @ajoberstar! :pray:
